# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src import ShimmerGrpcAndOJC_pb2 as src_dot_ShimmerGrpcAndOJC__pb2


class ShimmerServerStub(object):
    """The greeter service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/SayHello',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloRequest.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.FromString,
                )
        self.GetDataStream = channel.unary_stream(
                '/shimmerGRPC.ShimmerServer/GetDataStream',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StreamRequest.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ObjectCluster2.FromString,
                )
        self.SendDataStream = channel.stream_unary(
                '/shimmerGRPC.ShimmerServer/SendDataStream',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ObjectCluster2.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.FromString,
                )
        self.SendFileStream = channel.stream_unary(
                '/shimmerGRPC.ShimmerServer/SendFileStream',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.FileByteTransfer.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.FromString,
                )
        self.ConnectShimmer = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/ConnectShimmer',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
                )
        self.DisconnectShimmer = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/DisconnectShimmer',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
                )
        self.StartStreaming = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/StartStreaming',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
                )
        self.StopStreaming = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/StopStreaming',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
                )
        self.CloseApplication = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/CloseApplication',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
                )
        self.SetWorkspaceDirectory = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/SetWorkspaceDirectory',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.GetWorkspaceDirectory = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/GetWorkspaceDirectory',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                )
        self.GetDockedShimmerInfo = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/GetDockedShimmerInfo',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmersInfo.FromString,
                )
        self.GetMadgewickBetaValue = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/GetMadgewickBetaValue',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.DoubleMsg.FromString,
                )
        self.PairShimmers = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/PairShimmers',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.GetOperationProgress = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/GetOperationProgress',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.ImportSdDataFromShimmers = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/ImportSdDataFromShimmers',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.ParseSdDataFromPath = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/ParseSdDataFromPath',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.ScanSdDataAndCopy = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/ScanSdDataAndCopy',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.ClearSdCardData = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/ClearSdCardData',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.DockAccessSlotWithSdCard = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/DockAccessSlotWithSdCard',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.DockRestoreAutoTasks = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/DockRestoreAutoTasks',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
                )
        self.GetInfoSpans = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/GetInfoSpans',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.InfoSpans.FromString,
                )
        self.GetInfoAllShimmers = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/GetInfoAllShimmers',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmersInfo.FromString,
                )
        self.GetEmulatedDevices = channel.unary_unary(
                '/shimmerGRPC.ShimmerServer/GetEmulatedDevices',
                request_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
                response_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.EmulatedDevices.FromString,
                )


class ShimmerServerServicer(object):
    """The greeter service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataStream(self, request, context):
        """Client asking for data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendDataStream(self, request_iterator, context):
        """Client sending data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFileStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectShimmer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectShimmer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWorkspaceDirectory(self, request, context):
        """ConsensysApi related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspaceDirectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDockedShimmerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMadgewickBetaValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PairShimmers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperationProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportSdDataFromShimmers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseSdDataFromPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanSdDataAndCopy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearSdCardData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DockAccessSlotWithSdCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DockRestoreAutoTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfoSpans(self, request, context):
        """Shimmer device emulation software related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfoAllShimmers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmulatedDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShimmerServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloRequest.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.SerializeToString,
            ),
            'GetDataStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDataStream,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StreamRequest.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ObjectCluster2.SerializeToString,
            ),
            'SendDataStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SendDataStream,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ObjectCluster2.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.SerializeToString,
            ),
            'SendFileStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SendFileStream,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.FileByteTransfer.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.SerializeToString,
            ),
            'ConnectShimmer': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectShimmer,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.SerializeToString,
            ),
            'DisconnectShimmer': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectShimmer,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.SerializeToString,
            ),
            'StartStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStreaming,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.SerializeToString,
            ),
            'StopStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStreaming,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.SerializeToString,
            ),
            'CloseApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseApplication,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.SerializeToString,
            ),
            'SetWorkspaceDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWorkspaceDirectory,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'GetWorkspaceDirectory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspaceDirectory,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            ),
            'GetDockedShimmerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDockedShimmerInfo,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmersInfo.SerializeToString,
            ),
            'GetMadgewickBetaValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMadgewickBetaValue,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.DoubleMsg.SerializeToString,
            ),
            'PairShimmers': grpc.unary_unary_rpc_method_handler(
                    servicer.PairShimmers,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'GetOperationProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperationProgress,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'ImportSdDataFromShimmers': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportSdDataFromShimmers,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'ParseSdDataFromPath': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseSdDataFromPath,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'ScanSdDataAndCopy': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanSdDataAndCopy,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'ClearSdCardData': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearSdCardData,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'DockAccessSlotWithSdCard': grpc.unary_unary_rpc_method_handler(
                    servicer.DockAccessSlotWithSdCard,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'DockRestoreAutoTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.DockRestoreAutoTasks,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.SerializeToString,
            ),
            'GetInfoSpans': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfoSpans,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.InfoSpans.SerializeToString,
            ),
            'GetInfoAllShimmers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfoAllShimmers,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.ShimmersInfo.SerializeToString,
            ),
            'GetEmulatedDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmulatedDevices,
                    request_deserializer=src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
                    response_serializer=src_dot_ShimmerGrpcAndOJC__pb2.EmulatedDevices.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shimmerGRPC.ShimmerServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShimmerServer(object):
    """The greeter service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/SayHello',
            src_dot_ShimmerGrpcAndOJC__pb2.HelloRequest.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDataStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/shimmerGRPC.ShimmerServer/GetDataStream',
            src_dot_ShimmerGrpcAndOJC__pb2.StreamRequest.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.ObjectCluster2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendDataStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/shimmerGRPC.ShimmerServer/SendDataStream',
            src_dot_ShimmerGrpcAndOJC__pb2.ObjectCluster2.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendFileStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/shimmerGRPC.ShimmerServer/SendFileStream',
            src_dot_ShimmerGrpcAndOJC__pb2.FileByteTransfer.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConnectShimmer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/ConnectShimmer',
            src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectShimmer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/DisconnectShimmer',
            src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/StartStreaming',
            src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/StopStreaming',
            src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/CloseApplication',
            src_dot_ShimmerGrpcAndOJC__pb2.ShimmerRequest.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.CommandStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetWorkspaceDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/SetWorkspaceDirectory',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkspaceDirectory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/GetWorkspaceDirectory',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDockedShimmerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/GetDockedShimmerInfo',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.ShimmersInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMadgewickBetaValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/GetMadgewickBetaValue',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.DoubleMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PairShimmers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/PairShimmers',
            src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOperationProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/GetOperationProgress',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImportSdDataFromShimmers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/ImportSdDataFromShimmers',
            src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParseSdDataFromPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/ParseSdDataFromPath',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScanSdDataAndCopy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/ScanSdDataAndCopy',
            src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearSdCardData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/ClearSdCardData',
            src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DockAccessSlotWithSdCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/DockAccessSlotWithSdCard',
            src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DockRestoreAutoTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/DockRestoreAutoTasks',
            src_dot_ShimmerGrpcAndOJC__pb2.StringArrayMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.OperationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInfoSpans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/GetInfoSpans',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.InfoSpans.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInfoAllShimmers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/GetInfoAllShimmers',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.ShimmersInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmulatedDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shimmerGRPC.ShimmerServer/GetEmulatedDevices',
            src_dot_ShimmerGrpcAndOJC__pb2.StringMsg.SerializeToString,
            src_dot_ShimmerGrpcAndOJC__pb2.EmulatedDevices.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
