// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/ConsensysService_v0.0.1.proto

package com.shimmerresearch.managers.grpc.consensysservice;

public final class ShimmerConsensysService {
  private ShimmerConsensysService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/ConsensysService_v0.0.1.proto\022\020con" +
      "sensysservice\032\033src/ShimmerGrpcAndOJC.pro" +
      "to2`\n\020ConsensysService\022L\n\rGetDataStream\022" +
      "\032.shimmerGRPC.StreamRequest\032\033.shimmerGRP" +
      "C.ObjectCluster2\"\0000\001BM\n2com.shimmerresea" +
      "rch.managers.grpc.consensysserviceB\027Shim" +
      "merConsensysServiceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.shimmerresearch.grpc.ShimmerGRPC.getDescriptor(),
        });
    com.shimmerresearch.grpc.ShimmerGRPC.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
